# Generated by Django 4.0 on 2021-12-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pubdate', models.DateTimeField()),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='cocktails/')),
            ],
        ),
    ]
