# Generated by Django 4.0 on 2021-12-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktails',
            name='garnish',
            field=models.TextField(default='garnishes'),
        ),
        migrations.AddField(
            model_name='cocktails',
            name='taste',
            field=models.TextField(default='sweetsour'),
        ),
    ]
