# Generated by Django 4.0 on 2022-01-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktails',
            name='price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
