# Generated by Django 4.0 on 2022-01-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_cocktails_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktails',
            name='category',
            field=models.CharField(choices=[('M', 'Mocktails'), ('C', 'Cocktails')], default='C', max_length=1),
            preserve_default=False,
        ),
    ]
