# Generated by Django 4.0 on 2022-01-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_cocktails_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktails',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
