# Generated by Django 4.0 on 2022-01-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0006_cocktails_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktails',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
