# Generated by Django 4.0 on 2021-12-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Homepage',
        ),
    ]
