# Generated by Django 4.0 on 2021-12-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='summary',
            new_name='title',
        ),
    ]
