# Generated by Django 4.0 on 2021-12-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_summary_about_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Abouts',
        ),
    ]
